version: 0.2

phases:
  install:
    commands:
      - echo 'Intstalling Rspec...'
      - gem install rspec
  build:
    commands:
      - echo 'Build started on `date`'
      - rspec HelloWorld_spec.rb
  post_build:
    commands:
      - echo 'Build completed on `date`'
artifacts:
  files:
    - HelloWorld.rb